package com.mayabansi.webappdemo.domain;

// Generated Sep 19, 2010 12:31:53 AM by Hibernate Tools 3.3.0.GA

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Author generated by hbm2java
 */
@Entity
@Table(name = "author", catalog = "MockitoDemo1")
public class Author implements java.io.Serializable {

    private Long id;
    private long version;
    private String middleName;
    private Date dateOfBirth;
    private String lastName;
    private String firstName;
    private Date dateOfDeath;
    private String biography;

    public Author() {
    }

    public Author(String lastName, String firstName, String biography) {
        this.lastName = lastName;
        this.firstName = firstName;
        this.biography = biography;
    }

    public Author(String middleName, Date dateOfBirth, String lastName,
                  String firstName, Date dateOfDeath, String biography) {
        this.middleName = middleName;
        this.dateOfBirth = dateOfBirth;
        this.lastName = lastName;
        this.firstName = firstName;
        this.dateOfDeath = dateOfDeath;
        this.biography = biography;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version", nullable = false)
    public long getVersion() {
        return this.version;
    }

    public void setVersion(long version) {
        this.version = version;
    }

    @Column(name = "middle_name", length = 20)
    public String getMiddleName() {
        return this.middleName;
    }

    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date_of_birth", length = 19)
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }

    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    @Column(name = "last_name", nullable = false, length = 20)
    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Column(name = "first_name", nullable = false, length = 20)
    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date_of_death", length = 19)
    public Date getDateOfDeath() {
        return this.dateOfDeath;
    }

    public void setDateOfDeath(Date dateOfDeath) {
        this.dateOfDeath = dateOfDeath;
    }

    @Column(name = "biography", nullable = false)
    public String getBiography() {
        return this.biography;
    }

    public void setBiography(String biography) {
        this.biography = biography;
    }

}
