package com.mayabansi.webappdemo.domain;

// Generated Sep 19, 2010 12:31:53 AM by Hibernate Tools 3.3.0.GA

import javax.persistence.*;

/**
 * AuthorBook generated by hbm2java
 */
@Entity
@Table(name = "author_book", catalog = "MockitoDemo1")
public class AuthorBook implements java.io.Serializable {

    private AuthorBookId id;

    public AuthorBook() {
    }

    public AuthorBook(AuthorBookId id) {
        this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({
            @AttributeOverride(name = "authorBooksId", column = @Column(name = "author_books_id")),
            @AttributeOverride(name = "bookId", column = @Column(name = "book_id"))})
    public AuthorBookId getId() {
        return this.id;
    }

    public void setId(AuthorBookId id) {
        this.id = id;
    }

}
