package com.mayabansi.webappdemo.domain;

// Generated Sep 19, 2010 12:31:53 AM by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AuthorBookId generated by hbm2java
 */
@Embeddable
public class AuthorBookId implements java.io.Serializable {

    private Long authorBooksId;
    private Long bookId;

    public AuthorBookId() {
    }

    public AuthorBookId(Long authorBooksId, Long bookId) {
        this.authorBooksId = authorBooksId;
        this.bookId = bookId;
    }

    @Column(name = "author_books_id")
    public Long getAuthorBooksId() {
        return this.authorBooksId;
    }

    public void setAuthorBooksId(Long authorBooksId) {
        this.authorBooksId = authorBooksId;
    }

    @Column(name = "book_id")
    public Long getBookId() {
        return this.bookId;
    }

    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof AuthorBookId))
            return false;
        AuthorBookId castOther = (AuthorBookId) other;

        return ((this.getAuthorBooksId() == castOther.getAuthorBooksId()) || (this
                .getAuthorBooksId() != null
                && castOther.getAuthorBooksId() != null && this
                .getAuthorBooksId().equals(castOther.getAuthorBooksId())))
                && ((this.getBookId() == castOther.getBookId()) || (this
                .getBookId() != null
                && castOther.getBookId() != null && this.getBookId()
                .equals(castOther.getBookId())));
    }

    public int hashCode() {
        int result = 17;

        result = 37
                * result
                + (getAuthorBooksId() == null ? 0 : this.getAuthorBooksId()
                .hashCode());
        result = 37 * result
                + (getBookId() == null ? 0 : this.getBookId().hashCode());
        return result;
    }

}
