package com.mayabansi.webappdemo.domain;

// Generated Sep 19, 2010 12:31:53 AM by Hibernate Tools 3.3.0.GA

import javax.persistence.*;

/**
 * CartCartItem generated by hbm2java
 */
@Entity
@Table(name = "cart_cart_item", catalog = "MockitoDemo1")
public class CartCartItem implements java.io.Serializable {

    private CartCartItemId id;

    public CartCartItem() {
    }

    public CartCartItem(CartCartItemId id) {
        this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({
            @AttributeOverride(name = "cartCartItemsId", column = @Column(name = "cart_cart_items_id")),
            @AttributeOverride(name = "cartItemId", column = @Column(name = "cart_item_id"))})
    public CartCartItemId getId() {
        return this.id;
    }

    public void setId(CartCartItemId id) {
        this.id = id;
    }

}
