package com.mayabansi.webappdemo.domain;

// Generated Sep 19, 2010 12:31:53 AM by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CartCartItemId generated by hbm2java
 */
@Embeddable
public class CartCartItemId implements java.io.Serializable {

    private Long cartCartItemsId;
    private Long cartItemId;

    public CartCartItemId() {
    }

    public CartCartItemId(Long cartCartItemsId, Long cartItemId) {
        this.cartCartItemsId = cartCartItemsId;
        this.cartItemId = cartItemId;
    }

    @Column(name = "cart_cart_items_id")
    public Long getCartCartItemsId() {
        return this.cartCartItemsId;
    }

    public void setCartCartItemsId(Long cartCartItemsId) {
        this.cartCartItemsId = cartCartItemsId;
    }

    @Column(name = "cart_item_id")
    public Long getCartItemId() {
        return this.cartItemId;
    }

    public void setCartItemId(Long cartItemId) {
        this.cartItemId = cartItemId;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof CartCartItemId))
            return false;
        CartCartItemId castOther = (CartCartItemId) other;

        return ((this.getCartCartItemsId() == castOther.getCartCartItemsId()) || (this
                .getCartCartItemsId() != null
                && castOther.getCartCartItemsId() != null && this
                .getCartCartItemsId().equals(castOther.getCartCartItemsId())))
                && ((this.getCartItemId() == castOther.getCartItemId()) || (this
                .getCartItemId() != null
                && castOther.getCartItemId() != null && this
                .getCartItemId().equals(castOther.getCartItemId())));
    }

    public int hashCode() {
        int result = 17;

        result = 37
                * result
                + (getCartCartItemsId() == null ? 0 : this.getCartCartItemsId()
                .hashCode());
        result = 37
                * result
                + (getCartItemId() == null ? 0 : this.getCartItemId()
                .hashCode());
        return result;
    }

}
