package com.mayabansi.webappdemo.domain;

// Generated Sep 19, 2010 12:31:53 AM by Hibernate Tools 3.3.0.GA

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Cart generated by hbm2java
 */
@Entity
@Table(name = "cart", catalog = "MockitoDemo1")
public class Cart implements java.io.Serializable {

    private Long id;
    private long version;
    private double total;
    private double totalTax;
    private int totalQty;
    private double totalPrice;
    private List<CartItem> cartItemList;

    public Cart() {
    }

    public Cart(double total, double totalTax, int totalQty, double totalPrice) {
        this.total = total;
        this.totalTax = totalTax;
        this.totalQty = totalQty;
        this.totalPrice = totalPrice;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public Cart addToCart(CartItem cartItem) {
        if (cartItemList == null) {
            cartItemList = new ArrayList<CartItem>();
        }
        this.cartItemList.add(cartItem);
        return this;
    }

    public List<CartItem> getCartItems() {
        return this.cartItemList;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version", nullable = false)
    public long getVersion() {
        return this.version;
    }

    public void setVersion(long version) {
        this.version = version;
    }

    @Column(name = "total", nullable = false, precision = 22, scale = 0)
    public double getTotal() {
        return this.total;
    }

    public void setTotal(double total) {
        this.total = total;
    }

    @Column(name = "total_tax", nullable = false, precision = 22, scale = 0)
    public double getTotalTax() {
        return this.totalTax;
    }

    public void setTotalTax(double totalTax) {
        this.totalTax = totalTax;
    }

    @Column(name = "total_qty", nullable = false)
    public int getTotalQty() {
        return this.totalQty;
    }

    public void setTotalQty(int totalQty) {
        this.totalQty = totalQty;
    }

    @Column(name = "total_price", nullable = false, precision = 22, scale = 0)
    public double getTotalPrice() {
        return this.totalPrice;
    }

    public void setTotalPrice(double totalPrice) {
        this.totalPrice = totalPrice;
    }

}
