package com.mayabansi.webappdemo.domain;

// Generated Sep 19, 2010 12:31:53 AM by Hibernate Tools 3.3.0.GA

import javax.persistence.*;

/**
 * CustomerMainOrder generated by hbm2java
 */
@Entity
@Table(name = "customer_main_order", catalog = "MockitoDemo1")
public class CustomerMainOrder implements java.io.Serializable {

    private CustomerMainOrderId id;

    public CustomerMainOrder() {
    }

    public CustomerMainOrder(CustomerMainOrderId id) {
        this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({
            @AttributeOverride(name = "customerOrdersId", column = @Column(name = "customer_orders_id")),
            @AttributeOverride(name = "mainOrderId", column = @Column(name = "main_order_id"))})
    public CustomerMainOrderId getId() {
        return this.id;
    }

    public void setId(CustomerMainOrderId id) {
        this.id = id;
    }

}
