package com.mayabansi.webappdemo.domain;

// Generated Sep 19, 2010 12:31:53 AM by Hibernate Tools 3.3.0.GA

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * CustomerAddress generated by hbm2java
 */
@Entity
@Table(name = "customer_address", catalog = "MockitoDemo1")
public class CustomerAddress implements java.io.Serializable {

    private Long id;
    private long version;
    private String street2;
    private String street1;
    private String state;
    private String addressType;
    private long customerId;
    private String country;
    private String city;

    public CustomerAddress() {
    }

    public CustomerAddress(String street1, String state, String addressType,
                           long customerId, String country, String city) {
        this.street1 = street1;
        this.state = state;
        this.addressType = addressType;
        this.customerId = customerId;
        this.country = country;
        this.city = city;
    }

    public CustomerAddress(String street2, String street1, String state,
                           String addressType, long customerId, String country, String city) {
        this.street2 = street2;
        this.street1 = street1;
        this.state = state;
        this.addressType = addressType;
        this.customerId = customerId;
        this.country = country;
        this.city = city;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version", nullable = false)
    public long getVersion() {
        return this.version;
    }

    public void setVersion(long version) {
        this.version = version;
    }

    @Column(name = "street2", length = 20)
    public String getStreet2() {
        return this.street2;
    }

    public void setStreet2(String street2) {
        this.street2 = street2;
    }

    @Column(name = "street1", nullable = false, length = 20)
    public String getStreet1() {
        return this.street1;
    }

    public void setStreet1(String street1) {
        this.street1 = street1;
    }

    @Column(name = "state", nullable = false, length = 20)
    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    @Column(name = "address_type", nullable = false)
    public String getAddressType() {
        return this.addressType;
    }

    public void setAddressType(String addressType) {
        this.addressType = addressType;
    }

    @Column(name = "customer_id", nullable = false)
    public long getCustomerId() {
        return this.customerId;
    }

    public void setCustomerId(long customerId) {
        this.customerId = customerId;
    }

    @Column(name = "country", nullable = false, length = 20)
    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    @Column(name = "city", nullable = false, length = 20)
    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

}
