package com.mayabansi.webappdemo.domain;

// Generated Sep 19, 2010 12:31:53 AM by Hibernate Tools 3.3.0.GA

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * MainOrder generated by hbm2java
 */
@Entity
@Table(name = "main_order", catalog = "MockitoDemo1")
public class MainOrder implements java.io.Serializable {

    private Long id;
    private long version;
    private BigDecimal shipping;
    private BigDecimal totalBeforeTax;
    private Date orderDate;
    private Date estimatedDeliveryDate;
    private BigDecimal totalAmount;
    private BigDecimal totalTax;

    public MainOrder() {
    }

    public MainOrder(BigDecimal shipping, BigDecimal totalBeforeTax,
                     Date orderDate, Date estimatedDeliveryDate, BigDecimal totalAmount,
                     BigDecimal totalTax) {
        this.shipping = shipping;
        this.totalBeforeTax = totalBeforeTax;
        this.orderDate = orderDate;
        this.estimatedDeliveryDate = estimatedDeliveryDate;
        this.totalAmount = totalAmount;
        this.totalTax = totalTax;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version", nullable = false)
    public long getVersion() {
        return this.version;
    }

    public void setVersion(long version) {
        this.version = version;
    }

    @Column(name = "shipping", nullable = false)
    public BigDecimal getShipping() {
        return this.shipping;
    }

    public void setShipping(BigDecimal shipping) {
        this.shipping = shipping;
    }

    @Column(name = "total_before_tax", nullable = false)
    public BigDecimal getTotalBeforeTax() {
        return this.totalBeforeTax;
    }

    public void setTotalBeforeTax(BigDecimal totalBeforeTax) {
        this.totalBeforeTax = totalBeforeTax;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "order_date", nullable = false, length = 19)
    public Date getOrderDate() {
        return this.orderDate;
    }

    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "estimated_delivery_date", nullable = false, length = 19)
    public Date getEstimatedDeliveryDate() {
        return this.estimatedDeliveryDate;
    }

    public void setEstimatedDeliveryDate(Date estimatedDeliveryDate) {
        this.estimatedDeliveryDate = estimatedDeliveryDate;
    }

    @Column(name = "total_amount", nullable = false)
    public BigDecimal getTotalAmount() {
        return this.totalAmount;
    }

    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    @Column(name = "total_tax", nullable = false)
    public BigDecimal getTotalTax() {
        return this.totalTax;
    }

    public void setTotalTax(BigDecimal totalTax) {
        this.totalTax = totalTax;
    }

}
