package com.mayabansi.webappdemo.domain;

// Generated Sep 19, 2010 12:31:53 AM by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MainOrderOrderItemId generated by hbm2java
 */
@Embeddable
public class MainOrderOrderItemId implements java.io.Serializable {

    private Long mainOrderOrderItemsId;
    private Long orderItemId;

    public MainOrderOrderItemId() {
    }

    public MainOrderOrderItemId(Long mainOrderOrderItemsId, Long orderItemId) {
        this.mainOrderOrderItemsId = mainOrderOrderItemsId;
        this.orderItemId = orderItemId;
    }

    @Column(name = "main_order_order_items_id")
    public Long getMainOrderOrderItemsId() {
        return this.mainOrderOrderItemsId;
    }

    public void setMainOrderOrderItemsId(Long mainOrderOrderItemsId) {
        this.mainOrderOrderItemsId = mainOrderOrderItemsId;
    }

    @Column(name = "order_item_id")
    public Long getOrderItemId() {
        return this.orderItemId;
    }

    public void setOrderItemId(Long orderItemId) {
        this.orderItemId = orderItemId;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof MainOrderOrderItemId))
            return false;
        MainOrderOrderItemId castOther = (MainOrderOrderItemId) other;

        return ((this.getMainOrderOrderItemsId() == castOther
                .getMainOrderOrderItemsId()) || (this
                .getMainOrderOrderItemsId() != null
                && castOther.getMainOrderOrderItemsId() != null && this
                .getMainOrderOrderItemsId().equals(
                        castOther.getMainOrderOrderItemsId())))
                && ((this.getOrderItemId() == castOther.getOrderItemId()) || (this
                .getOrderItemId() != null
                && castOther.getOrderItemId() != null && this
                .getOrderItemId().equals(castOther.getOrderItemId())));
    }

    public int hashCode() {
        int result = 17;

        result = 37
                * result
                + (getMainOrderOrderItemsId() == null ? 0 : this
                .getMainOrderOrderItemsId().hashCode());
        result = 37
                * result
                + (getOrderItemId() == null ? 0 : this.getOrderItemId()
                .hashCode());
        return result;
    }

}
