package com.mayabansi.webappdemo.domain;

// Generated Sep 19, 2010 12:31:53 AM by Hibernate Tools 3.3.0.GA

import javax.persistence.*;

/**
 * MainOrderOrderItem generated by hbm2java
 */
@Entity
@Table(name = "main_order_order_item", catalog = "MockitoDemo1")
public class MainOrderOrderItem implements java.io.Serializable {

    private MainOrderOrderItemId id;

    public MainOrderOrderItem() {
    }

    public MainOrderOrderItem(MainOrderOrderItemId id) {
        this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({
            @AttributeOverride(name = "mainOrderOrderItemsId", column = @Column(name = "main_order_order_items_id")),
            @AttributeOverride(name = "orderItemId", column = @Column(name = "order_item_id"))})
    public MainOrderOrderItemId getId() {
        return this.id;
    }

    public void setId(MainOrderOrderItemId id) {
        this.id = id;
    }

}
