package com.mayabansi.webappdemo.domain;

// Generated Sep 19, 2010 12:31:53 AM by Hibernate Tools 3.3.0.GA

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * OrderItem generated by hbm2java
 */
@Entity
@Table(name = "order_item", catalog = "MockitoDemo1")
public class OrderItem implements java.io.Serializable {

    private Long id;
    private long version;
    private double total;
    private double shipping;
    private double price;
    private double tax;
    private long qty;
    private String productType;

    public OrderItem() {
    }

    public OrderItem(double total, double shipping, double price, double tax,
                     long qty, String productType) {
        this.total = total;
        this.shipping = shipping;
        this.price = price;
        this.tax = tax;
        this.qty = qty;
        this.productType = productType;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version", nullable = false)
    public long getVersion() {
        return this.version;
    }

    public void setVersion(long version) {
        this.version = version;
    }

    @Column(name = "total", nullable = false, precision = 22, scale = 0)
    public double getTotal() {
        return this.total;
    }

    public void setTotal(double total) {
        this.total = total;
    }

    @Column(name = "shipping", nullable = false, precision = 22, scale = 0)
    public double getShipping() {
        return this.shipping;
    }

    public void setShipping(double shipping) {
        this.shipping = shipping;
    }

    @Column(name = "price", nullable = false, precision = 22, scale = 0)
    public double getPrice() {
        return this.price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    @Column(name = "tax", nullable = false, precision = 22, scale = 0)
    public double getTax() {
        return this.tax;
    }

    public void setTax(double tax) {
        this.tax = tax;
    }

    @Column(name = "qty", nullable = false)
    public long getQty() {
        return this.qty;
    }

    public void setQty(long qty) {
        this.qty = qty;
    }

    @Column(name = "product_type", nullable = false)
    public String getProductType() {
        return this.productType;
    }

    public void setProductType(String productType) {
        this.productType = productType;
    }

}
